name: Build docker image

on:
  workflow_call:
    outputs:
      IMAGE:
        description: "Docker image"
        value: ${{ jobs.build.outputs.IMAGE }}

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      IMAGE: ${{ steps.docker-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build and push docker image
        # Versjonsoversikt (tag -> SHA): https://github.com/nais/docker-build-push/tags
        # Denne SHA-en: https://github.com/nais/docker-build-push/commit/31c3a7321909bcb20799fdf46153fec721fd9512
        uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512 # v0
        id: docker-push
        with:
          team: tpts
